In [1]:
import scipy.io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
mat = scipy.io.loadmat(r'C:\Study Material\Coursera Assignment\assignments_of_coursera\machine-learning-ex3\ex3\ex3data1.mat')
X = mat["X"]
Y = mat["y"]
theta = scipy.io.loadmat(r'C:\Study Material\Coursera Assignment\assignments_of_coursera\machine-learning-ex3\ex3\ex3weights.mat')

In [3]:
print(X,Y,X.shape,Y.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]] (5000, 400) (5000, 1)


In [4]:
theta1 = theta["Theta1"]

In [5]:
X = X.T

In [6]:
X = np.vstack((np.ones(len(X[1])),X))

In [7]:
a = np.dot(theta1,X)

In [8]:
a = 1/(1+ np.exp(-a))

In [9]:
a = np.vstack((np.ones(len(a[1])),a))

In [10]:
theta2 = theta["Theta2"]

In [11]:
hx = np.dot(theta2,a)

In [12]:
hx = 1/(1+np.exp(-hx))

In [13]:
hx

array([[1.12661530e-04, 4.79026796e-04, 8.85702310e-05, ...,
        5.17641791e-02, 8.30631310e-04, 4.81465717e-05],
       [1.74127856e-03, 2.41495958e-03, 3.24266731e-03, ...,
        3.81715020e-03, 6.22003774e-04, 4.58821829e-04],
       [2.52696959e-03, 3.44755685e-03, 2.55419797e-02, ...,
        2.96297510e-02, 3.14518512e-04, 2.15146201e-05],
       ...,
       [4.01468105e-04, 2.39107046e-03, 6.22892325e-02, ...,
        2.15667361e-03, 1.19366192e-02, 5.73434571e-03],
       [6.48072305e-03, 1.97025086e-03, 5.49803551e-03, ...,
        6.49826950e-01, 9.71410499e-01, 6.96288990e-01],
       [9.95734012e-01, 9.95696931e-01, 9.28008397e-01, ...,
        2.42384687e-05, 2.06173648e-04, 8.18576980e-02]])

In [14]:
X = X.T

In [15]:
test = X[23].reshape(401,1)

In [16]:
na = np.dot(theta1,test)

In [17]:
na = 1/(1+np.exp(-na))

In [18]:
na.shape

(25, 1)

In [19]:
na = np.vstack((np.ones(len(na[1])),na))

In [20]:
hx = np.dot(theta2,na)

In [21]:
hx = 1/(1+np.exp(-hx))

In [22]:
np.argmax(hx)

9

In [23]:
Y[23][0]

10